/*

 BIRD.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char bird[] =
{
  0x00,0x0C,0x00,0x1E,0x84,0x1A,0xF9,0x07,
  0xF8,0x06,0x00,0x7C,0x28,0x28,0x00,0x00
};

/* End of BIRD.C */
